version: '3.9'
services:
  next:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - next
    networks:
      - app-network

  certbot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
