version: '3.9'
services:
  next:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - next
    networks:
      - app-network
    volumes:
      - ./docker/cert.sh:/usr/local/bin/cert.sh
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
