version: '3.9'
services:
  next:
    image: next:latest
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500M    # Лимит памяти для next
        reservations:
          memory: 400M    # Резерв памяти для next
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
networks:
  app-network:
    driver: overlay
