version: '3.9'
services:
  next:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/certbot/www/:/var/www/certbot/
    depends_on:
      - next
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/letsencrypt/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
