FROM nginx:stable

RUN apt-get update && \
    apt-get install -y python3-certbot-nginx && \
    rm -rf /var/lib/apt/lists/*

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the script for certificate generation and renewal
COPY ./docker/cert.sh /usr/local/bin/cert.sh
RUN chmod +x /usr/local/bin/cert.sh

CMD ["/bin/bash", "-c", "/usr/local/bin/cert.sh && nginx -g 'daemon off;'"]
