FROM certbot/certbot:v2.8.0

# Копируем скрипт для получения и обновления сертификатов
COPY ./docker/entrypoint-certbot.sh /usr/local/bin/entrypoint-certbot.sh

# Устанавливаем разрешения на выполнение скрипта
RUN chmod +x /usr/local/bin/entrypoint-certbot.sh

# Устанавливаем точку входа на скрипт
ENTRYPOINT ["/usr/local/bin/entrypoint-certbot.sh"]
