FROM nginx:stable

RUN apt-get update && \
    apt-get install -y python3-certbot-nginx && \
    rm -rf /var/lib/apt/lists/*

COPY ./docker/nginx.conf /etc/nginx/nginx.conf

RUN certbot --nginx --non-interactive --agree-tos --email admin@quizerplay.com -d quizerplay.com

CMD ["nginx", "-g", "daemon off;"]
