name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 104.131.51.32 >> ~/.ssh/known_hosts

      - name: Copy repository to server
        run: |
          rsync -avz --exclude '.git' ./ root@104.131.51.32:/srv/quizlet

      # 4. Деплой
      - name: Deploy application
        run: |
          ssh user@your-server-ip << 'EOF'
          cd /srv/quizlet

          # Пересборка Docker-образа
          docker build -t next:latest .

          # Перезапуск сервиса
          docker service update --force app_next
          EOF
