name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 104.131.51.32 >> ~/.ssh/known_hosts

      - name: Pull repository to server
        run: |
          ssh root@104.131.51.32 << 'EOF'
          cd /srv/quizlet
          git pull origin master
          EOF

      - name: Build Docker image
        run: |
          ssh root@104.131.51.32 << 'EOF'
          cd /srv/quizlet
          docker build -t next:$TAG . || { echo 'Docker build failed'; exit 1; }
          docker service update --image next:$TAG app_next || { echo 'Service update failed'; exit 1; }
          EOF

      - name: Finishing deploy application
        run: |
          ssh root@104.131.51.32 << 'EOF'

          docker system prune -f
          echo "Docker system prune completed."

          docker ps -a

          docker service ps app_next
          EOF
